.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "JSITBAD" "1" "May 2015" "" ""
.
.SH "NAME"
\fBjsitbad\fR \- classify \.js files as malicious or legitimate
.
.SH "SYNOPSIS"
\fBjsitbad\fR \fBadd\fR [\-f] [(\-m|\-l|\-u) [message]] \fIdatabase\fR \fIjs\-file\fR
.
.P
\fBjsitbad\fR \fBfit\fR [\-o \fIoutput\-file\fR] \fIdatabase\fR
.
.P
\fBjsitbad\fR \fBpredict\fR (\-f \fIhash\-file\fR|\fIhash\fR \.\.\.| \fIjs\-file\fR \.\.\.) [\-o \fIjson\-file\fR] \-i (\fIdatabase\fR|\fItraining\fR)
.
.SH "DESCRIPTION"
\fBjsitbad\fR tries to assess the malignity of JavaScript snippets (or whole files)\. Details about the algorithm should appear in a paper that I have yet to write\.
.
.P
The \fBadd\fR command adds a snippet in the \fIdatabase\fR (See section \fIDATABASE\fR)\. If no message is specified, a default one is constructed from the username, hostname and the date\. The \fBmessage\fR argument should include information about the file (e\.g\. its origin), its malignity (e\.g\. who did the assessment, what is the modus operandi, how certain are we about the assessment) etc\.
.
.P
\fBadd\fR\-ing a snippet that already exists in the database is not always an error:
.
.IP "\(bu" 4
If the snippet\'s status is the same as the given \fB\-m\fR, \fB\-l\fR or \fB\-u\fR flag, the metadata of the snippet is updated to reflect the fact that the snippet was seen again\.
.
.IP "\(bu" 4
If the existing snippet\'s status is different from the given flag and no \fImessage\fR is provided, the command will always fail\.
.
.IP "\(bu" 4
If the existing snippet\'s status is unknown, and the \fB\-m\fR or \fB\-l\fR flag is provided, the snippet is moved to the appropriate subdirectory and its metadata is updated accordingly\.
.
.IP "\(bu" 4
If the existing snippet\'s status is malicious or legitimate, its status will change only if the \fB\-f\fR flag is provided\.
.
.IP "" 0
.
.P
The \fBfit\fR command trains the classifer on the specified \fIdatabase\fR\. Information about the training, such as various assessments of the performance will be printed on \fBstdout\fR or in \fIoutput\-file\fR if specified\. Some files will be written in a subdirectory of the \fIdatabase\fR directory, to be used by \fBpredict\fR\. The name of the subdirectory is of the form \fBYYYYMMDDHHSS_training\fR\. It is untested if files in this directory can be used across machines\. See the \fIBUGS\fR section about that\.
.
.P
For vizualization purposes, the \fBfit\fR command creates a \.svg file in the training directory, which contains all the samples as dots and the classifier output as color zones\.
.
.P
The \fBpredict\fR command tells the user whether some snippets are malicious or legitimate\. The snippets are referenced either by their sha1 hash (either one per line in a file if the \fB\-f\fR option is used, or in a space separated list on the command line) or by their filename (one snippet per file)\.
.
.P
\fBpredict\fR first checks if the file exists in the database\. If it does and its metadata is up to date, it will output that without computing anything\. If the file does not exist or if its metadata is obsolete, \fBpredict\fR will run the latest classifier in \fIdatabase\fR (or alternatively the classifier in the user\-specified \fItraining\fR directory) on the snippet and output (either on \fBstdout\fR or on the file specified with the \fB\-o\fR option) one JSON object per snippet\.
.
.P
If a snippet given to \fBpredict\fR is not already in the \fIdatabase\fR, \fBpredict\fR will be add it, the same way calling \fBadd \-u\fR would\.
.
.P
This object contains information about the classification, mainly an assessment of the file (\'malicious\' or \'legitimate\'), a classification score (a float between 0 and 1, closest to 1 if the file looks malicious), information about vizualization (e\.g\. coordinates in a 2D plot)\.
.
.P
This object is appended by \fBpredict\fR to the \.json file that contains the metadata of the snippet\.
.
.SH "OPTIONS"
\fBadd\fR command:
.
.IP "\(bu" 4
\fB\-f\fR force change : allow the user to change a snippet status from malicious or legitimate
.
.IP "\(bu" 4
\fB\-m\fR mark the file as malicious
.
.IP "\(bu" 4
\fB\-l\fR mark the file as legitimate
.
.IP "\(bu" 4
\fB\-u\fR (default) mark the file\'s status as unknown
.
.IP "" 0
.
.P
\fBfit\fR command:
.
.IP "\(bu" 4
\fB\-o\fR specify an output file, defaults to \fBstdout\fR if unspecified
.
.IP "" 0
.
.P
\fBpredict\fR command:
.
.IP "\(bu" 4
\fB\-f\fR specify a file to read hashes from, one hash per line
.
.IP "\(bu" 4
\fB\-o\fR specify an output file, defaults to \fBstdout\fR if unspecified
.
.IP "\(bu" 4
\fB\-i\fR specify which database or training directory to use
.
.IP "" 0
.
.SH "DATABASE"
\fBjsitbad\fR\'s database consists of three directories :
.
.IP "\(bu" 4
\fBmalicious\fR: malicious files
.
.IP "\(bu" 4
\fBlegitimate\fR: legitimate files
.
.IP "\(bu" 4
\fBunknown\fR: files of unknown status
.
.IP "" 0
.
.P
Each of those directories contains the JavaScript files, whose name is the sha1 checksum of the code inside with the \fB\.js\fR extension (e\.g\. \fBffabce78341dc27fc7993efadd46fa54fbcb55dc\.js\fR)\.
.
.P
Every JavaScript file should be accompanied by a \fB\.json\fR file that bears the same name except for the extension and holds metadata about the JavaScript snippet\. Such metadata can include the user\-specified or machine\-generated message at the time of addition, information about previous runs of \fBpredict\fR and \fBfit\fR and information about occurences of this snippet in the wild\.
.
.SH "SYNTAX"
.
.SH "ENVIRONMENT"
.
.SH "RETURN VALUES"
.
.SH "STANDARDS"
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "BUGS"
.
.IP "\(bu" 4
The JSON schema for the metadata and the output of \fBpredict\fR is not written, although this may be a feature and not a bug after all\.
.
.IP "\(bu" 4
It is unknown whether the files written by \fBfit\fR are portable across machines\. Training directories should therefore not be sent, transferred nor saved to version control\. Instead, the database should be transferred and the \fBfit\fR command run again\.
.
.IP "" 0
.
.SH "HISTORY"
.
.SH "AUTHOR"
Joint work @sekoia\.fr
.
.SH "COPYRIGHT"
.
.SH "SEE ALSO"
.
.SH "DESCRIPTION"
.
.SH "TODO"

